#!/bin/bash
#SBATCH --partition=p.cmfe
#SBATCH --ntasks=80
#SBATCH --constraint='[swi1|swi1|swi2|swi3|swi4|swi5|swi6|swi7|swi8|swi9|swe1|swe2|swe3|swe4|swe5|swe6|swe7]'
#SBATCH --time=5760
#SBATCH --output=time.out
#SBATCH --error=error.out
#SBATCH --job-name=pi_18675694
#SBATCH --chdir=/cmmc/u/hmai/project-NiGBs-New/Ni-PureGBs-GammaShift-Relax2/S3_RA110_S1_12__a_0_4__b_0_2_hdf5/S3_RA110_S1_12__a_0_4__b_0_2
#SBATCH --get-user-env=L

source /etc/profile.d/modules.sh

module load intel/18.0.5
module load impi/2018.4
#module load /cmmc/system_sle15_sp1/modules.addon/CMMC/oldvasp/5.3.5

/usr/bin/srun -n $SLURM_NPROCS vasp

/usr/bin/gzip POTCAR
rm CHGCAR WAVECAR CHG IBZKPT PCDAT EIGENVAL PROCAR DOSCAR XDATCAR
/usr/bin/gzip OSZICAR
